### PR TITLE
Adding Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by brunopulis**
What this PR propose:

Translate to Brazilian portuguese:

* _data;
* _shared-content;

This PR closes the #18

### CODE REVIEW

**Comment by hidde** [comment]
Fantastic, thanks for adding!

Would you mind also updating the language in the table in the [readme](https://github.com/hidde/eleventy-wcag-reporter#supported-languages)?

**Comment by brunopulis** [comment]
> Fantastic, thanks for adding!
> 
> Would you mind also updating the language in the table in the [readme](https://github.com/hidde/eleventy-wcag-reporter#supported-languages)?

For sure! :)

**Comment by brunopulis** [comment]
@hidde done! 👍🏻

**Comment by hidde** [comment]
Thanks! 

I'm not familiar, so correct me if I'm wrong, but it looks like language code for Brazilian Portuguese is `pt-br`/`pt-BR`, should we use that instead as the key?

**Comment by brunopulis** [comment]
> Thanks!
> 
> I'm not familiar, so correct me if I'm wrong, but it looks like language code for Brazilian Portuguese is `pt-br`/`pt-BR`, should we use that instead as the key?

You're right, I completely forgot about it. I will correct and send the PR again.

**Comment by hidde** [comment]
Thanks a lot for your work on this. Looks good to me!

**Pull request merged**
